### DISCUSSION TITLE
Inline image breaking line

### DISCUSSION THREAD

**Discussion by ptram** [typst/typst#2239] [General]
### Description

Hi,

I'm trying to render to PDF though Quarto. Images inserted in a line of text break the line before and after the image. This code:

```
---
title: "test"
format:
  typst:
    toc: true
    columns: 1
    papersize: a5
    fontsize: 9.5pt
---

## Title 2

the [page menu ![](images/page-menu-icon.png){width=3mm}]{custom-style="Parameter"}.

```

is converted by Pandoc to Typst as follows:

```
> quarto pandoc -t typst
the [page menu ![](images/page-menu-icon.png){width=3mm}]{custom-style="Parameter"}. The various commands
^Z
the page menu #image("images/page-menu-icon.png", width: 3mm).  The various commands

```

The resulting PDF shows a line broken before and after the inline image:

![](https://user-images.githubusercontent.com/19186065/270190029-6f3d9776-3cdd-43fb-ba7b-b4399207a586.png)

By reading the docs, I don't see any limitation about adding images inline. Is this a bug?

Quarto and Pandoc are the latest version (Quarto is the beta version 1.4.x).

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst
