### DISCUSSION TITLE
Add support for importing remote repositories

### DISCUSSION THREAD

**Discussion by iilyak** [typst/typst#3125] [Ideas]
I've noticed the discussion about adding support for importing from URL [here](https://github.com/typst/typst/discussions/2658), but I couldn't find the discussion about importing from repositories. 

Quite a few projects allow importing remote assets

- [ffizer](https://ffizer.github.io/ffizer/book/template_configuration.html) - uses repository based approach
  ```yaml
  imports:
  - uri: "git@github.com:ffizer/templates_default.git"
    rev: "master"
    subfolder: "gitignore_io"
  ```
- [aquaproj](https://aquaproj.github.io/docs/develop-registry/create-private-registry/) - uses registry/lock file approach
   ```yaml
   # registry.yaml
   packages:
   - type: github_release
     repo_owner: suzuki-shunsuke
     repo_name: tfcmt
     asset: 'tfcmt_{{.OS}}_{{.Arch}}.tar.gz'
   ```
- [go-task](https://taskfile.dev/experiments/remote-taskfiles/) - experimenting with URL based approach
  ```yaml
   version: '3'
   includes:
      my-remote-namespace: https://raw.githubusercontent.com/my-org/my-repo/main/Taskfile.yml
  ```
