### DISCUSSION TITLE
How do I read typst code as a string from a file, and insert it into another file and have it executed?

### DISCUSSION THREAD

**Discussion by beyarkay** [typst/typst#3417] [Q&A] [answered]
I have a YAML file, and one of the values has typst code:

```yaml
---
foo: "bar"
desc: |
  - this is typst code
  - these dashes should be intepreted by typst
  - even though YAML parsers see this whole block as one long string
```

I want to extract the `desc` and insert it into a typst doc. I can get the data, no problem:

```typst
let data = yaml(filename)
```

but if I try access the `desc` key, I can't figure out how to tell typst that the string should be formatted as typst code?

```
#text(data.desc)
```
doesn't work, and neither does `#data.desc`.
