### DISCUSSION TITLE
How to script for the boxes in a column?

### DISCUSSION THREAD

**Discussion by ghost** [typst/typst#4878] [General]
How can I send content to specific boxes or a column?

For example, say I have a rudimentary dictionary that looks like this

``` yaml

Items:
-
  Section: Foo
  Details:
    ABCD: EFGH
    HIJK: KLMN
-
  Section: Bar
  Details:
    OPQR: STUV
    WXYZ: 1234
- 
  Section: Tres
  Details:
      Random: Thought
      Test: Value


```

And I am calling it using code that looks like this:-

``` typst

#let content = yaml("dictionary.yaml") // Get the content file

#let test_item(test_item) = {
  [
    *#underline[#test_item.Section]* \
    #for (hit, details) in test_item.Details [
      *#hit* : #details \
    ] #v(-0.25em) // Add some space for the next section
  ]
}

#box(height: 75pt,
 columns(2, gutter: 11pt)[
    #set par(justify: true)
    #for entry in content.Items {
      test_item(entry)
    }
 ]
)


```

Is there a way I can direct content to specific boxes in the column.
What function/utility of script should I be reading into?

This does not have to be done with \`columns\` if there is some other
way to script what specific section of the page content ends up in.
