### ISSUE TITLE
APA citing multiple authors doesn't follow set language (and instead of und)

### ISSUE THREAD

**Issue by Regenhardt** [typst/typst#1075]
### Description

Citing multiple authors in a german text joins the authors using "and" instead of "und", which doesn't make sense in a german text.

Example Hayagriva declaration:

```
hascher-brandenberger:
    type: Book
    title: Emotionen und Lernen im Unterricht. In Bildung und Emotion
    page-range: 289-310
    author: 
      - Hascher, T.
      - Brandenberger, C. C.
    date: 2018
    doi: 10.1007/978-3-658-18589-3_16
    publisher: Springer Fachmedien Wiesbaden
```

Example text: 

`Wie von #cite("hascher-brandenberger", brackets: false) beschrieben...`

Expected output:

`Wie von Hascher und Brandenberger (2018) beschrieben...`

Actual output:

`Wie von Hascher and Brandenberger (2018) beschrieben...`

### Operating system

Web app, Windows

### Typst version

- [X] I am using the latest version of Typst
