### ISSUE TITLE
More citation styles

### ISSUE THREAD

**Issue by clbarnes** [typst/typst#132]
Excited to get to use typst, it's a great-looking tool in a space which sorely needed innovation.

It would be really helpful to have an equivalent to natbib's `\citeyear`, `\citeauthor` etc. for including information from references in free-flowing text. Perhaps something like a `#citefield(myref, field: date.year)`? Although something more terse would also go down well.

**Comment by kevin-nel** [comment]
it might be nice if there were support for [citation style language](https://citationstyles.org/), which is an open source specification for bibliographies and reference styles. There are many styles available from [zotero](https://www.zotero.org/styles).

**Comment by tanloong** [comment]
Another reference manager [Jabref](https://docs.jabref.org/) takes a BibTeX file as input and makes the citation and bibliography super customizable through a [style file](https://docs.jabref.org/cite/openofficeintegration#the-style-file). I think this is a good example to follow.

**Comment by flavioabar** [comment]
Typst is great and I would like to adopt it for all my LaTeX type documents. I started doing my beamer type presentations with typst and it's great and very easy to maintain. Now, for other types of documents (reports, articles,...), I am still stuck with LaTeX because the bibliography is hard-coded in typst and I need flexibility. Thanks for considering @tanloong's request 🙏

**Comment by flavioabar** [comment]
> Typst is great and I would like to adopt it for all my LaTeX type documents. I started doing my beamer type presentations with typst and it's great and very easy to maintain. Now, for other types of documents (reports, articles,...), I am still stuck with LaTeX because the bibliography is hard-coded in typst and I need flexibility. Thanks for considering @tanloong's request pray

I started a fork of [typst/typst](https://github.com/typst/typst) (see [flavioabar/typst](https://github.com/flavioabar/typst)) and added a new style for APS citation style (Physics journals). For doing so, I also forked [typst/typst](https://github.com/typst/hayagriva) (see [flavioabar/typst](https://github.com/flavioabar/hayagriva)) . I'm still testing everithing (the code is dirty and takes the 'ieee' style as basis), however the style is fully usable under 'faa' name (to be renamed later on). I also included new features to #bibliography() such as fine tuning the number of authors before 'et al.', the possibility to highligh an author, and clickable links to the corresponding papers in the journal names:

Bibliography exemple:

```YAML
AbreuAraujo2012:
  type: article
  url: "http://link.aps.org/doi/10.1103/PhysRevB.86.064424"
  date: 2012
  doi: 10.1103/PhysRevB.86.064424
  parent:
    - type: periodical
      title:
        value: Phys. Rev. B
        sentence-case: Phys. rev. b
      issue: 6
      publisher: American Physical Society
      volume: 86
  author:
    - "Abreu Araujo, Flavio"
    - "Darques, Michaël"
    - "Zvezdin, Konstantin A."
    - "Khvalkovskiy, Alexey V."
    - "Locatelli, Nicolas"
    - "Bouzehouane, Karim"
    - "Cros, Vincent"
    - "Piraux, Luc"
  title: "Microwave signal emission in spin-torque vortex oscillators in metallic nanowires: Experimental measurements and micromagnetic numerical study"
  page-range: 64424
```

In `typst`:
```rust
#bibliography(style: "faa", etalth: 3, author: "Abreu Araujo",  "db.yml")
```

Output:

**F. Abreu Araujo**, M. Darques, K. A. Zvezdin _et al._, [_Phys. Rev. B_](https://doi.org/10.1103/PhysRevB.86.064424) **86**, 6 (2012).

You can test (install) my version of typst as follows:

```bash
cargo install --git https://github.com/flavioabar/typst --branch dev
```

Later, I will try to find time to clean my code and propose a PR to integrate this style that I will probably rename as 'aps' ([ASP citation style](https://www.citethisforme.com/citation-generator/american-physics-society)) in 'typst/hayagriva' and 'typst/typst'.
