### ISSUE TITLE
one-off error in citing web url in bibliography apa format

### ISSUE THREAD

**Issue by Sycration** [typst/typst#1650]
### Description

In main.typ:
```
#cite("huh")
#bibliography("huh.yml", style: "apa")
```

In huh.yml
```yml
huh:
  type: Web
  title: Webpage
  date: 2023-01-01
  url: 
    value: https://example.com
    date: 2023-01-01
```

What renders:
![image](https://github.com/typst/typst/assets/48634717/3a55734b-cec2-4723-9ebb-6bd93e9ea149)

Strangely it works fine in mla format
![image](https://github.com/typst/typst/assets/48634717/0ec673ef-f8b4-4965-a290-786963f358c1)

### Reproduction URL

https://typst.app/project/ruVWFQsdcauNF8BzYanN_e

### Operating system

Web app

### Typst version

- [x] I am using the latest version of Typst
