### ISSUE TITLE
Allow packages limited file access

### ISSUE THREAD

**Issue by jneug** [typst/typst#1836]
### Description

For security reasons, packages are restricted to accessing files from their own directory. Arbitrary file access can be exploited to get access to sensitive information and should be prohibited. But as packages and templates get more complicated and feature rich, some limited file access could be useful.

In most cases, access to a limited number of clearly defined files would be enough to make this feature useful. 

I propose the addition of a new `files` key to the `typst.toml`, that is set to an array of files relative to the compilation root. The package gets read-only access to the specified files.

For example:

```toml
[package]
name = "mantys"
version = "0.0.3"
entrypoint = "mantys.typ"
authors = ["J. Neugebauer"]
license = "MIT"
description = "Helpers to build manuals for Typst packages."
repository = "https://github.com/jneug/typst-mantys"
files = ["theme.toml", "typst.toml"]
```

This way, only limited file access is granted, and the accessed files can easily be reviewed by package users. 

In addition, I propose to add a `default` argument to the file access functions `read`, `toml`, `yaml` and `csv`. If it is present, the functions won't throw an error, when the file is missing, but returns the default value. This would allow an easy fallback for packages. 

### Use Case

This would be useful to make packages and templates more flexible to adapt to the users' needs. A template could load a `theme.toml` file, to make the color palette customizable, or a serial letter template could load address data from `customers.csv`. 

A template for creating manuals (like [Mantys](https://github.com/jneug/typst-mantys)) could read a packages' `typst.toml`, to automatically add version and author information to the document.
