### ISSUE TITLE
Wrong bibliography order - first two digits of year ignored when sorting (using "alphanumerical" style only)

### ISSUE THREAD

**Issue by danaugrs** [typst/typst#2221]
### Description

For example, a bibliography entry dated 1902 is listed after one dated 2001. This only happens when using the "alphanumerical" citation style. Full example:

```
#cite("test1", "test2", style: "alphanumerical")
#bibliography("references.yml", title: "References", style: "ieee")
```

```
test1:
  title: Test1
  date: 1995
  author: Foo

test2:
  title: Test2
  date: 2003
  author: Bar
```

In the example above `test2` is listed before `test1`. If I change from "alphanumerical" to "numerical" then `test1` is listed before `test2` as expected.

Discord discussion: https://discord.com/channels/1054443721975922748/1155551192752062705

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst
