### ISSUE TITLE
Crash reported when modifying date in Hayagriva file

### ISSUE THREAD

**Issue by wpkelso** [typst/typst#2553]
### Description

When a bibliography is already included in the `.typ` file and the date of an entry in a hayagriva file is modified, a crash is reported every time the file is compiled.
```typ
#bibliography("bib.yml", full: true)
```

```yaml
tdx-whitepaper:
  type: report
  title: "White Paper: Intel(r) Trust Domain Extensions"
  date: 2023-02
  organization: "Intel(r)"
  url: https://www.intel.com/content/www/us/en/developer/tools/trust-domain-extensions/documentation.html

sgx-brief:
  type: report
  title: "Product Brief: Intel(r) Software Guard Extensions"
  date: 2022-03-03
  organization: "Intel(r)"
  url: https://www.intel.com/content/www/us/en/content-details/723693/product-brief-intel-software-guard-extensions.html

confidential-compute:
  type: blog
  title: "Rising to the Challenge — Data Security with Intel Confidential Computing"
  author: Anil Rao
  date: 2022-01-20
```

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst
