### ISSUE TITLE
Bibliography handles "$" weirdly

### ISSUE THREAD

**Issue by genericusername3** [typst/typst#2669]
### Description

I'm using the bibliography function to display the following bibliography item:

```yaml
amazon-outage-costs:
  type: article
  title: Amazon ‘missed out on $34m in sales during internet outage’
  author:
  - Chapman, Ben
  date: 2021-06-08
  url:
    value: "https://www.independent.co.uk/news/business/amazon-down-internet-outage-sales-b1861737.html"
    date: 2023-11
  parent:
    type: periodical
    title: Independent.co.uk
    publisher: Independent
```

The output looks like this:
![grafik](https://github.com/typst/typst/assets/42579023/cdf211c7-6105-422e-be80-4f31035c83e8)

The Unicode quotes are handled correctly, but the dollar sign seems to be interpreted as the beginning of math mode. Replacing with `\$` or `\\$` to escape the dollar sign results in the title being truncated:
![grafik](https://github.com/typst/typst/assets/42579023/f6075b1f-bd40-44f3-8210-9f11c232166d)
![grafik](https://github.com/typst/typst/assets/42579023/f6980b1f-453b-4b9b-a180-02b77f0f3a1f)

What does work, however, is using math mode to display a dollar sign:
```yaml
  title: `Amazon ‘missed out on $dollar$34m in sales during internet outage’
```

---

I think text in bibliographies should not be parsed for math instructions, because titles don't usually include math formatting.

### Operating system

Web app

### Typst version

- [X] I am using the latest version of Typst
