### ISSUE TITLE
Some entries in thesis and report bibliography items are not shown

### ISSUE THREAD

**Issue by gdietl** [typst/typst#2833]
### Description

When citing a Master Thesis or Technical Report, only the author(s), the title and the year is shown. Information about the institution/school and the month of the publication are not printed. I converted the corresponding bib-files into yml-files using hayagriva and all information is correct there. So, it seems to be a problem of the CSL file. However, I tried a couple of different style files and couldn't resolve the problem.

### Typst version

- [X] I am using the latest version of Typst

**Comment by Enivex** [comment]
Have you checked this in main / 0.10 preview?

**Comment by gdietl** [comment]
I checked it with the latest git version, i.e. typst 0.9.0 (79c2d1f2). Will this be fixed in 0.10?

**Comment by zepinglee** [comment]
Can you provide a minimal reproducible example?

**Comment by gdietl** [comment]
Using the following bib-file
```
@techreport{report1,
author = {Robert Swearingen},
title = {Morpholoty and syntax of British sailors’ English},
series = {Technical Report},
number = {249},
institution = {Profanity Institute},
address = {New York, NY},
year = {1985}
}

@techreport{report2,
author = {Robert Swearingen},
title = {Morpholoty and syntax of British sailors’ English},
series = {Technical Report},
number = {249},
publisher = {Profanity Institute},
address = {New York, NY},
year = {1985}
}

@mastersthesis{thesis,
title        = {A Study of Example},
author       = {Jane Doe},
year         = 2022,
month        = {June},
address      = {Example City, CA},
note         = {Available at \url{https://example.com/thesis.pdf}},
school       = {University of Example},
type         = {Master thesis}
}
```
and the typst-file
```
@report1 @report2 @thesis

#bibliography("ref.bib")
```
yields
![image](https://github.com/typst/typst/assets/112486210/3fbc8256-059b-4d01-9d80-8b7e9f2c1f66)

Using hayagriva to produce the yml-file yields
```
report1:
  type: report
  title: Morpholoty and syntax of British sailors’ English
  author: Swearingen, Robert
  date: 1985
  location: New York, NY
  organization: Profanity Institute
  issue: 249
  parent:
    type: report
    title: Technical Report
report2:
  type: report
  title: Morpholoty and syntax of British sailors’ English
  author: Swearingen, Robert
  date: 1985
  publisher: Profanity Institute
  location: New York, NY
  issue: 249
  parent:
    type: report
    title: Technical Report
thesis:
  type: thesis
  title: A Study of Example
  author: Doe, Jane
  date: 2022-06
  location: Example City, CA
  organization: University of Example
```

So, you see that the yml-file is produced correctly while the presentation in the resulting pdf is not.
