### ISSUE TITLE
DOI not available in CSL

### ISSUE THREAD

**Issue by timon-schelling** [typst/typst#2961]
### Description

doi is referenced in the csl file but not printed.

![image](https://github.com/typst/typst/assets/36821505/d95fa220-04e4-49ff-b0ec-48df83a9e6f4)

section in main.csl
```
<text variable="DOI" prefix="doi:" suffix=", "/>
<text variable="URL"/>
```
refs.yaml
```
bartels2005:
  type: Article
  title: "Homer Gets a Tax Cut: Inequality and Public Policy in the American Mind"
  author: "Bartels, Larry M."
  date: 2005
  publisher: "Perspectives on Politics"
  doi: "10.1017/s1537592705050036"
  url:
    value: "https://doi.org/10.1017/s1537592705050036"
    date: "2023-12-06"
  page-range: 15-31
  volume: 3
  number: 1
  issn: "15375927, 15410986"
```

csl works with https://editor.citationstyles.org/visualEditor/

![image](https://github.com/typst/typst/assets/36821505/88a806f8-510f-433e-92d3-eec28ff02358)

### Reproduction URL

https://typst.app/project/rYTX-2xTFEVZl8eKErcj8O

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst
