### ISSUE TITLE
Reference does not render custom Figure numbering

### ISSUE THREAD

**Issue by twrightsman** [typst/typst#3089]
### Description

```
#figure(
  lorem(5),
  caption: [#lorem(5)],
  kind: "figure-supplemental",
  supplement: [Figure],
  numbering: "S1",
) <fig_s1>

@fig_s1
```

The above results in "Figure 1" being rendered in the reference instead of "Figure S1", though the figure caption is correct.

![bug](https://github.com/typst/typst/assets/6300973/5dde4a19-e43f-4bd5-8e65-fecec825ce77)

As far as I can tell this isn't the same as https://github.com/typst/typst/issues/2980, but should have been implemented in https://github.com/typst/typst/pull/491?

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
The reason seems to be numbering trimming. If you change it to `SI`, it does print "Figure I". This means the numbering pattern is used, but the "S" is trimmed from it. The idea of trimming is that `numbering: "1."` should still yield a reference `Section 1` rather than `Section 1.`. Apparently, it also trims at the start but that wasn't intentional.

**Comment by twrightsman** [comment]
https://github.com/typst/typst/blob/4e5afa672f502d53e931d432ec1a36bdc6e16583/crates/typst/src/model/numbering.rs#L185-L187

It seems prefixes are trimmed?

I can see how this makes sense in cases like Section `(I)`, but not for the case of `S1`.

**Comment by laurmaedje** [comment]
> I can see how this makes sense in cases like Section (I), but not for the case of S1.

For sure. Maybe we could just trim punctuation. I'm not sure how to deal with it.

**Comment by twrightsman** [comment]
Perhaps another parameter to the respective functions (figure, etc), that disables numbering trimming?

Not the most elegant solution, but could work.

**Comment by simbafs** [comment]
I encounter the same problem when I need to custom numbering. I am wonder if this issue has any solution?

**Comment by EirikTengesdal** [comment]
> I encounter the same problem when I need to custom numbering. I am wonder if this issue has any solution?

@simbafs: After spending hours on trying to make my custom numbering (for supplemental figures, tables etc.) work, I found the following workaround solution partially based on the great suggestions in #3871, especially [this post](https://github.com/typst/typst/discussions/3871#discussioncomment-9018697), and in #2990.

I had to remove the following whitespace from the `separator` variable, since it appears to have a hardcoded space in [its definition](https://github.com/typst/typst/blob/c4dd6fa06227b8c4a04cf488f371f52d5379ef9b/crates/typst/src/model/figure.rs#L529C1-L539C6) for English (`Lang::ENGLISH | _ => ": ",`).

I have done this via Quarto YAML – and due to incompatibilities as of now (Typst support for `space-between-numbering` in Quarto is planned, see https://github.com/quarto-dev/quarto-cli/issues/9416, cf. https://github.com/quarto-dev/quarto-cli/discussions/9413) between Quarto HTML and Typst output, I added crossref arguments for both. Here, I use Typst with the [quarto-preprint](https://github.com/mvuorre/quarto-preprint) extension.

YAML excerpt:
```
---
format:
  html:
    crossref:
      custom:
        - kind: float
          key: sfig
          latex-env: sfig
          caption-prefix: Figure S
          reference-prefix: Fig. S
          space-before-numbering: false
          latex-list-of-description: Supplementary Figure
  preprint-typst:
    crossref:
      custom:
        - kind: float
          key: sfig
          latex-env: sfig
          reference-prefix: "Figure"
          space-before-numbering: false
          latex-list-of-description: Supplementary Figure
    include-in-header:
      - text: |
          #set figure(
            numbering: n => [S#n]
          )
          
          #show figure.caption: c => [
            #c.supplement.text #c.counter.display(c.numbering)#c.separator.text.replace(": ", ":")#c.body
            ]
          
          #set ref(supplement: it => {
            if it.func() == figure {
              text("Fig.")
            }
          })
    keep-typ: true
---
```

I am a complete novice in Typst, but I assume one could directly paste the following code to a relevant part of a `.typ` file:
```typst
#set figure(
  numbering: n => [S#n]
)

#show figure.caption: c => [
  #c.supplement.text #c.counter.display(c.numbering)#c.separator.text.replace(": ", ":")#c.body
  ]

#set ref(supplement: it => {
  if it.func() == figure {
    text("Fig.")
  }
})
```
