### ISSUE TITLE
Bibliography URL flakyness

### ISSUE THREAD

**Issue by JeffreyAnimal** [typst/typst#3620]
### Description

After compiling of a Project, multiline URLs in the Citation section are not stable.
When hovering on the String, the full URL is previewed, but when hovering inbetween lines, only the URL-Part of one Line is selected and resulting in a not found Page.

![broken link](https://github.com/typst/typst/assets/120835312/57c642f4-df3c-49ef-8106-8e1d2ee7eb8b)

### Reproduction URL

https://typst.app/project/pi56q7eeJLk6i4S-gBET5u

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst

**Comment by laurmaedje** [comment]
Looks like a duplicate of https://github.com/typst/typst/issues/3478 and https://github.com/typst/typst/issues/2587.

**Comment by laurmaedje** [comment]
Okay, I've taken another look and maybe we can fix this by just expanding the link box slightly.

cc: @EpicEricEE @edu-baer @PgBiel (from the other issues)

**Comment by yruellan** [comment]
Hi,

I was looking to reproduce this issue with the following code:

```typ
= Introduction

#lorem(10)

Source @very_long_source

#bibliography("biblio.yml")
```

```yaml
very_long_source:
    type: Web
    title: A very long source url
    url: https://www.example.com/this/is/a/very/long/source/url/that/keeps/going/on/and/on/and/on/and/on/and/on/and/on/and/on/and/on/and/on/and/on?parameter1=long_value&parameter2=another_long_value&parameter3=yet_another_long_value&parameter4=and_so_on
```

It seems that the URL is not being truncated in the output and that the full URL is being displayed. (I'm using the Preview application on macOS to view the PDF.)

Do the issue still exist? 

<img width="884" alt="Image" src="https://github.com/user-attachments/assets/a01cc5da-c759-4843-8a16-70d39a58231e" />
