### ISSUE TITLE
`typst check`

### ISSUE THREAD

**Issue by Leedehai** [typst/typst#3792]
### Description

I wish there's a `typst check` command (or `typst compile --no-emit`/`typst compile --check-only`) that checks the _validity_ of the files but short of outputing the PDF.

By _validity_ I mean emitting all the errors possible. As folks pointed out in the Discord channel, it is more than just running the parser, but also the eval phase, and maybe later phase that could emit errors.

### Use Case

It brings the same benefits like `cargo check` for Rust projects, and is an idiomatic way to validate the input files for users and Typst developers alike.

**Comment by Enter-tainer** [comment]
i guess typst compile --dry-run might make more sense.

 typst is already pretty fast. and as you mentioned, check should go through all stages. i think check should have similar time usage

**Comment by tingerrr** [comment]
> i guess typst compile --dry-run might make more sense.

One problem with this is that it would make the cli more "complex", as the option changes which arguments are required.

> typst is already pretty fast. and as you mentioned, check should go through all stages. i think check should have similar time usage

Export can be non-trivially slow for large documents, so this could still be a substantial win for large throughput.

**Comment by laurmaedje** [comment]
In the future, PDF export might also produce errors (at least if e.g. PDF/A is required), so the question is how that would interact with a potential `check` command.

**Comment by bluebear94** [comment]
Note that in Rust, [`cargo check` might not catch all errors](https://rust-lang.github.io/rfcs/3477-cargo-check-lang-policy.html) possible in `cargo build`.

**Comment by janosh** [comment]
`typst compile --dry-run` would be very useful for things like `pre-commit` hooks. [currently using this hacky](https://github.com/janosh/diagrams/blob/2c244e6237e02a45a64876e41363c414db14d8e7/.pre-commit-config.yaml#L83-L91) solution of sending output to `mktemp` files:

```yml
- id: validate-typst
  name: Validate Typst files compile without errors
  language: rust
  # exit 255 to fail on first compile error https://stackoverflow.com/a/26485626/4034025
  # use mktemp to send output to /var/folders/... to avoid modifying existing files
  entry: bash -c 'for x in "$@"; do typst compile "$x" $(mktemp).pdf || exit 255; done' --
  files: \.typ$
  types: [file]
  additional_dependencies: [typst]
```
