### ISSUE TITLE
Inconsistent styling with `bibliography.full: true`

### ISSUE THREAD

**Issue by tingerrr** [typst/typst#3986]
### Description

When using `bilbiography(full: true, ...)` to show all references, the styling seems to be inconsistent when a cite style like `alphanumeric` is used. The markers fall back to the `biliography` style (`ieee` in my case).

|`full: true` without explicit `cite`|`full: true` with explicit `cite`|
|---|---|
|![image](https://github.com/typst/typst/assets/137803093/09348406-b62d-4bf0-9d3e-bfc7a1206086)|![image](https://github.com/typst/typst/assets/137803093/4f245880-b047-48ed-a560-981b3529276e)|

I assume this is because `alphanumeric` is a style on `cite` only, so the lack of cite elements means the styling isn't applied.

At face value, I can see that this "works as intended", but I never understood (or asked) why `alphanumeric` is only a style on `cite` in the first place.

I did not attempt minimizing this, but this should suffice:

```typst
#set cite(style: "alphanumeric")
#bilbiography(full: true, "bib.yaml")

// cite some key always to enforce the style
#cite("some-key")

// comment this out to observe the difference
#for key in yaml("bib.yaml") {
  cite(label(key))
}
```

Tested using `typst 0.11.0 (1e645b39)`.

### Operating system

Linux

### Typst version

- [ ] I am using the latest version of Typst

**Comment by JakobSachs** [comment]
Able to replicate this in the webapp (url: https://typst.app/project/rNnLsTjkhkCnV5I0HqrvQb)
But had to unpack the iteration to key-value since the provided example-code doesn't compile:

```typst
#set cite(style: "alphanumeric")
#bibliography(full: true, "bib.yaml")

// cite some key always to enforce the style
#cite(<harry>)

// comment this out to observe the difference
#for (key,value) in yaml("bib.yaml") {
  cite(label(key))
}
```

bib.yaml (example taken from https://github.com/typst/hayagriva/blob/main/docs/file-format.md)
```yaml
harry:
    type: Book
    title: Harry Potter and the Order of the Phoenix
    author: Rowling, J. K.
    volume: 5
    page-total: 768
    date: 2003-06-21

electronic:
    type: Web
    title: Ishkur's Guide to Electronic Music
    serial-number: v2.5
    author: Ishkur
    url: http://www.techno.org/electronic-music-guide/
```

---

Before commenting out iteration over keys:
<img width="479" alt="Screenshot 2024-04-24 at 11 09 27" src="https://github.com/typst/typst/assets/28728963/a81d21d4-8826-4ae8-bbb3-6f01e81bc87f">

After commenting out the iteration:
<img width="493" alt="Screenshot 2024-04-24 at 11 09 40" src="https://github.com/typst/typst/assets/28728963/6905cbd3-17f4-4b57-88ea-4d6d716a61a7">

---

Looks like un-intended/buggy behaviour to me.
