### ISSUE TITLE
Bibliography links broken on main

### ISSUE THREAD

**Issue by EpicEricEE** [typst/typst#4408]
### Description

Since #4352, citations do not link to their respective bibliography entry but instead to the start of the document. The backreference still works correctly.

**Example:**
<table>
<tr>
<th>Typst Code</th>
<th>Bibliography</th>
</tr>
<tr>
<td>

```typ
#set page(height: 3cm, width: 9cm)

#lorem(20)

@citation

#bibliography("bibliography.yaml")
```

</td>
<td>

```yaml
citation:
  type: Article
  title: A sample citation
  author: John Doe
  date: 2019-01
```

</td>
</tr>
</table>

PDF Output: [example.pdf](https://github.com/user-attachments/files/15866684/example.pdf)

### Operating system

Windows

### Typst version

- [X] I am using the latest version of Typst
