### ISSUE TITLE
 Narrative citation for two authors with APA uses `&` instead of `and`

### ISSUE THREAD

**Issue by poopsicles** [typst/typst#4549]
### Description

Using Typst version 0.11.1 with a bibliography entry with two authors and attempting to render in the "prose" format shows it in the format `a & b (year)` instead of `a and b (year)`.

From [Author–Date Citation System](https://apastyle.apa.org/style-grammar-guidelines/citations/basic-principles/author-date):

> Parenthetical citation: (Salas & D’Agostino, 2020)
> Narrative citation: Salas and D’Agostino (2020)

However with Typst, compiling:

```yaml
# ref.yml

markov:
  type: article
  title: A Sequence-based Selection Hyper-heuristic Utilising a Hidden Markov Model
  author:
    - Kheiri, Ahmed
    - Keedwell, Ed
  date: 2015
  page-range: 417-424
  url: https://doi.org/10.1145/2739480.2754766
  serial-number:
    doi: 10.1145/2739480.2754766
    isbn: "9781450334723"
  abstract: Selection hyper-heuristics are optimisation methods that operate at the level above traditional (meta-)heuristics. Their task is to evaluate low level heuristics and determine which of these to apply at a given point in the optimisation process. Traditionally this has been accomplished through the evaluation of individual or paired heuristics. In this work, we propose a hidden Markov model based method to analyse the performance of, and construct, longer sequences of low level heuristics to solve difficult problems. The proposed method is tested on the well known hyper-heuristic benchmark problems within the CHeSC 2011 competition and compared with a large number of algorithms in this domain. The empirical results show that the proposed hyper-heuristic is able to outperform the current best-in-class hyper-heuristic on these problems with minimal parameter tuning and so points the way to a new field of sequence-based selection hyper-heuristics.
  parent:
    type: proceedings
    title: Proceedings of the 2015 Annual Conference on Genetic and Evolutionary Computation
    publisher: Association for Computing Machinery
    location: Madrid, Spain
    parent:
      type: proceedings
      title: GECCO '15
```

```typ
// main.typ

A sequence-based heuristic selection strategy (SSHH) was presented in the work of
#cite(<markov>, form: "prose") and applied to the domain of high school timetabling. 

#bibliography(
  "ref.yml",
  title: "References",
  style: "american-psychological-association",
)
```

Results in:

```text
A sequence‑based heuristic selection strategy (SSHH) was presented in the work of 
Kheiri & Keedwell (2015) and applied to the domain of high school timetabling. 
```

![image](https://github.com/typst/hayagriva/assets/87488715/6d30e327-fb7a-4d59-a9c1-60525123f250)

I'm not sure if this is a problem with the CSL, or Hayagriva itself, but maybe I'll try to check later.

### Operating system

Web app, macOS

### Typst version

- [X] I am using the latest version of Typst
