### ISSUE TITLE
@Citation makes first word of title lowercase in escaped Hayagriva entry

### ISSUE THREAD

**Issue by HawksDarris** [typst/typst#4660]
### Description

Hayagriva entry:  

```
ukraine: 
  type: video
  title: "'Russia Is Not Going To Lose The War': JD Vance Blasts Senate Voting To Send Funding To Ukraine"
  date: 2024-02-14
  url: 
    value: https://www.youtube.com/watch?v=W53wILyEyEc
    date: 2024-08-02 
```

document.typ: 

```
Blah blah blah @ukraine 
```

Expected result: The title should appear as 'Russia Is Not Going To Lose The War': JD Vance Blasts Senate Voting To Send Funding To Ukraine

Result (regardless of citation style): The title appears as 'russia Is Not Going To Lose The War': JD Vance Blasts Senate Voting To Send Funding To Ukraine

### Operating system

Linux

### Typst version

- [X] I am using the latest version of Typst
