### ISSUE TITLE
Inconsistent `show` behavior for reference links

### ISSUE THREAD

**Issue by miles-1** [typst/typst#4962]
### Description

I think I'm seeing inconsistent `show` behavior for reference links. If I try to `show` all `ref`s to be blue, those created by a user-defined function containing `cite` do not seem to be styled. See example below:

```typ
#set math.equation(
  numbering: "(1)"
)
#show ref: i => {
  text(blue, i)
}
#let ref_eqn(labl) = ref(labl)
#let ref_ctn(labl) = cite(labl)

$ a = b = c $  <eq1>

Ref equation with \@ symbol: @eq1
Ref equation with user-defined function: #ref_eqn(<eq1>)
Ref citation with \@ symbol: @dependence
Ref citation with user-defined function: #ref_ctn(<dependence>)

#bibliography("citations.yml", style: "apa")
```

... with `citations.yml` having the following data...

```yml
dependence:
    type: Article
    title: The program dependence graph and its use in optimization
    author: ["Ferrante, Jeanne", "Ottenstein, Karl J.", "Warren, Joe D."]
    date: 1987-07
    serial-number:
        doi: "10.1145/24039.24041"
    parent:
        type: Periodical
        title: ACM Transactions on Programming Languages and Systems
        volume: 9
        issue: 3
```

... gives this output:

![Screenshot 2024-09-15 at 11 47 58 AM](https://github.com/user-attachments/assets/57abb39f-95d4-4616-8c88-48bad8ba83f6)

Why would the final link not be colored blue?

### Reproduction URL

https://typst.app/project/r6ZUviFmvpdMzcVuKp4sE5

### Operating system

macOS

### Typst version

- [X] I am using the latest version of Typst
