### ISSUE TITLE
Citation title with Vietnamese character causes crash

### ISSUE THREAD

**Issue by ichxorya** [typst/typst#499]
How to recreate:
- Create a .yml file for bibliography:
```
bodua:
  type: Web
  title: Câu chuyện bó đũa
  url: http://thyendong.vinhphuc.edu.vn/chuyen-muc/cau-chuyen-bo-dua-truyen-ngu-ngon-viet-nam-c18146-736776.aspx
```
- Cite this in a typst file.

Edit: Fixed
