### ISSUE TITLE
Allow documents and modules to register artificial or pre-configured font-families

### ISSUE THREAD

**Issue by terefang** [typst/typst#5455]
### Description

today in CSS i can:

```css
@font-face {
  font-family: Conduit;
  src: url("./conduit-itc-std.otf");
  font-style: normal;
}

@font-face {
  font-family: Conduit;
  src: url("./conduit-itc-std-bold.otf");
  font-weight: bold;
}

@font-face {
  font-family: Conduit;
  src: url("./conduit-itc-std-italic.otf");
  font-style: italic;
}

@font-face {
  font-family: Conduit;
  src: url("./conduit-itc-std-bolditalic.otf");
  font-weight: bold;
  font-style: italic;
}
```

could this be supported in typst with script similar to:
```
#font.face(family: "Conduit", src: "./conduit-itc-std.otf", style: "normal")
#font.face(family: "Conduit", src: "./conduit-itc-std-bold.otf", weight: "bold")
#font.face(family: "Conduit", src: "./conduit-itc-std-italic.otf", style: "italic")
#font.face(family: "Conduit", src: "./conduit-itc-std-bolditalic.otf", weight: "bold", style: "italic")
```

### Use Case

prior art would be the CSS spec.

the actual use-cases would be:

* document project(s) that bring their own fonts.
* installable module(s) that bring their own fonts.
* pandoc templates that bring their own fonts.
