### ISSUE TITLE
Bibliography entries don't justify consistently

### ISSUE THREAD

**Issue by ironupiwada** [typst/typst#5898]
### Description

I've been using Typst 0.13-rc1 on Tinymist (VSCode, pre-released, MacOS). I've noticed that bibliographic entries generated using the APA style don't justify consistently at all (to be precise, they should reach the whole text width). Moreover, the problem persists regardless of the style (I've also tried with MLA and Chicago, for example). I'm attaching some Hayagriva YAML code and screenshots demonstrating the issue.

```
Aarseth_Cybertekst_2014:
  type: book
  title: Cybertekst. Spojrzenie na literaturę ergodyczną
  author: Aarseth, Espen
  date: 2014
  parent:
    type: original
    date: 1997
  affiliated:
    names:
    - Pisarski, Mateusz
    - Sikora, Dorota
    - Schreiber, Paweł
    - Tabaczyński, Michał
    role: translator
  publisher: 
    name: '{Korporacja Ha!art – Miejskie Centrum Kultury w Bydgoszczy}'
    location: '{Kraków – Bydgoszcz}'
Aarseth_Badanie_2010:
  type: chapter
  title: 'Badanie zabawy: metodologia analizy gier'
  author: Aarseth, Espen
  date: 2010
  page-range: 13–37
  parent:
    type: book
    editor: Filiciak, Mirosław
    title: Światy z pikseli. Antologia studiów nad grami komputerowymi
    publisher: 
      name: Wydawnictwo SWPS Academica
      location: Warszawa
    parent:
      type: original
      date: 2003
  affiliated:
    - names: Filiciak, Mirosław
      role: translator
Aarseth_A_2012:
  type: article
  title: A {Narrative Theory} of {Games}
  author: Aarseth, Espen
  date: 2012-05-29
  editor: Seif El-Nasr, Magy
  page-range: 129–133
  serial-number:
    doi: 10.1145/2282338.2282365
    isbn: 978-1-4503-1333-9
  abstract: 'This paper presents a narrative theory of games, building on standard narratology, as a solution to the conundrum that has haunted computer game studies from the start: How to approach software that combines games and stories?'
  parent:
    type: proceedings
    title: Proceedings of the {International Conference} on the {Foundations} of {Digital Games}
    publisher: 
      name: '{Association for Computing Machinery}'
      location: '{New York}'
Aarseth_I_2014:
  type: chapter
  title: '{I Fought the Law: Transgressive Play and the Implied Player}'
  author: Aarseth, Espen
  date: 2014
  editor:
  - Segal, Naomi
  - Kolevaa, Daniela
  page-range: 180–188
  url: http://dx.doi.org/10.1057/9781137429704_13
  serial-number:
    doi: 10.1057/9781137429704_13
  parent:
    type: book
    title: '{From Literature to Cultural Literacy}'
    publisher: 
      name: Palgrave Macmillan UK
      location: London
```

<img width="410" alt="Image" src="https://github.com/user-attachments/assets/c73ac73a-01cd-4b2a-919e-a62bd837309f" />

<img width="427" alt="Image" src="https://github.com/user-attachments/assets/087000be-e779-467f-8afa-4ee298b3b733" />

### Operating system

macOS

### Typst version

- [x] I am using the latest version of Typst
