### ISSUE TITLE
Two consecutive APA citations of one person lose the release date

### ISSUE THREAD

**Issue by ironupiwada** [typst/typst#6066]
### Description

Consider the following example:

```
#lorem(5) @Freud_Poza_1997@Freud_Pisma_1998

#bibliography("main.yaml", style: "american-psychological-association")
```

Coupled with the YAML Hayagriva citations:

```
Freud_Poza_1997:
  type: book
  title: Poza zasadą przyjemności
  author: Freud, Sigmund
  date: 1997
  parent:
    type: original
    date: 1920
  affiliated:
    names: Prokopiuk, Jerzy
    role: translator
  publisher: 
    name: PWN
    location: Warszawa
Freud_Pisma_1998:
  type: chapter
  title: Aktualne uwagi o wojnie i śmierci
  author: Freud, Sigmund
  date: 1998
  affiliated:
    names:
    - Poręba, Marcin
    - Ochocki, Aleksander
    - Reszke, Robert
    role: translator
  page-range: 25–50
  parent:
    type: book
    title: Pisma społeczne
    author: Freud, Sigmund
    publisher: 
      name: KR
      location: Warszawa
    parent:
      type: original
      date: 1915
```

it gives the following result:

<img width="640" alt="Image" src="https://github.com/user-attachments/assets/89ebe97e-ec61-4953-93bb-c9a81598d484" />

Strikingly, the second source throws the original date but not the actual edition date. Meanwhile, it should result in (Freud 1920/1997; 1915/1998).

### Operating system

macOS

### Typst version

- [x] I am using the latest version of Typst
