### ISSUE TITLE
Linguify doesn't work partly on Typst.app but working on Tinymist Typst.

### ISSUE THREAD

**Issue by ertugruluyar-github** [typst/typst#6189]
### Description

As describe in [utype-neuies-reports > Selecting One of the Alternatives in Headings with Alternatives](https://github.com/typst/packages/tree/main/packages/preview/utype-neuies-reports/1.2.0#selecting-one-of-the-alternatives-in-headings-with-alternatives).

This working in Tinymist Typst but when I tested on Typst.app, it didn't work. I refresh the project and also trigger to repreview.

I have used the [Linguify](https://typst.app/universe/package/linguify) package for this.
I don't know what is the source of the issue whether Typst.app or Linguify.

https://github.com/typst-community/linguify/issues/26

### Reproduction URL

https://typst.app/project/wnpBT8JmBCihFbUfPUaxpL

### Operating system

Windows 11

### Typst version

- [x] I am using the latest version of Typst

**Comment by ertugruluyar-github** [comment]
I debug the issue and:
When I use this:
```typst
#import "/src/lib.typ": (
  template-configurations,
  LANGUAGES,
  REPORT-TYPES,
  DEPARTMENTS,
  PROGRAMS,
  ACADEMIC-MEMBER-TITLES,
)
```
instead of this:
```typst
#import "@preview/utype-neuies-reports:1.2.0": (
  template-configurations,
  LANGUAGES,
  REPORT-TYPES,
  DEPARTMENTS,
  PROGRAMS,
  ACADEMIC-MEMBER-TITLES,
)
```
the issue gone.

The issue couldn't that Linguify doesn't installed because changing the language is working with Languify.

**Comment by Enivex** [comment]
What does not work exactly?

**Comment by ertugruluyar-github** [comment]
> What does not work exactly?

Thank you @Enivex.
For example, in the `/template/assets/languages/english.toml` file, you can select the desired heading by making the following change:
```toml
[translations]
# To use only one of the headings, select either the expression not in parentheses or one of the expressions in parentheses and delete the others.
# Before selection:
#PREFACE = "PREFACE (ACKNOWLEDGEMENTS)"
# After selection:
PREFACE = "PREFACE"
```

User can override some language values, they only need to modify the languages files in the template folder.
