### ISSUE TITLE
Code syntaxes does not work with include statements

### ISSUE THREAD

**Issue by maleadt** [typst/typst#6310]
### Description

I'm trying to highlight Julia REPL code, which consists of a `julia>` prefix followed by Julia code. I can successfully highlight regular Julia code by using the [existing Julia syntax highlighting rules for Sublime](https://github.com/JuliaEditorSupport/Julia-sublime/blob/master/Julia.sublime-syntax), but there isn't an existing definition for Julia REPL code yet, so I set out to develop my own.

To avoid repeating the contents of the existing Julia definitions in my Julia REPL definitions, I want to use [the `include` functionality](https://www.sublimetext.com/docs/syntax.html#including-an-external-prototype) from Sublime Text's syntax definitions. After a bit of fiddling, I came up with:

```yaml
%YAML 1.2
---
# Syntax highlighting for Julia REPL output

name: Julia-REPL
first_line_match: ^julia>
scope: source.julia-repl

contexts:
  main:
    # "julia>" prompt
    - match: '^(julia>)(\s*)'
      captures:
        1: string.quoted.single.julia  # make it green
        2: punctuation.whitespace.prompt.julia-repl # capture whitespace
      push:
        # now handle the code that follows
        - meta_scope: meta.code.julia.repl
        # If a line does NOT start with 6 spaces (continuation)
        # AND does NOT start with a new "julia>" prompt,
        # then it's considered the end of the Julia code block (likely output or EOF).
        - match: '^(?!(?:\s{6}|julia>))'
          pop: true
        # REPL input continues when starting with 6 spaces (and no new prompt)
        - match: '^(\s{6})(?!julia>)'
          captures:
            1: punctuation.whitespace.leading.continuation.julia-repl
        - include: scope:source.julia

    # anything else is considered output, and should not be formatted
    - match: '^(.*)\n?'
      scope: comment.line.julia.repl-output
```

This seems to work fine when I check it with the `syncat` example from syntect; if I put both the existing Julia definitions and the above one in a folder I can highlight the following demo file:

```julia
julia> 1+1
2

julia> "test"
"test"
```

<img width="437" alt="Image" src="https://github.com/user-attachments/assets/527db283-d667-4ad3-be50-b4dfdb51a398" />

Yet if I try this in Typst, I don't get the expected output:

``````typst
#set raw(syntaxes: ("assets/julia.sublime-syntax", "assets/julia-repl.sublime-syntax"))

```julia-repl
julia> 1+1
2

julia> "test"
"test"
```
``````

<img width="115" alt="Image" src="https://github.com/user-attachments/assets/a831bb39-cecd-47dc-b2e4-b100524918a8" />

Note how the `julia>` prompt _is_ green, and the output _has_ been colored as a comment, so the Julia-REPL syntax by itself seems to work. Highlighting the code as regular Julia code also works, so the problem doesn't seem to be with the Julia syntax highlighting rules. Instead, something seems up with how the external `include` works, even though it is supported fine by syntect itself.

### Operating system

Linux

### Typst version

- [x] I am using the latest version of Typst

**Comment by dblsaiko** [comment]
The "scope:*" syntax in general doesn't seem to work. I have a similar file:

```yaml
%YAML 1.2
---
name: Console
scope: text
version: 2

contexts:
  main:
    - match: '^(\(.*?\))?\s*([%#])\s*'
      captures:
        1: comment.inline
        2: keyword.operator
      embed: scope:source.bash
      embed_scope: markup.italic
      escape: '(?<!\\)$'
    - match: '^  ...$'
      scope: comment.line
```

along with roughly using it like this:

````typst
#set raw(syntaxes: "Console.yaml")

```Console
(systemd-run) % loginctl
SESSION  UID USER  SEAT  LEADER CLASS         TTY   IDLE SINCE
  ...
      4 1000 saiko seat0 1383   user          pts/2 no   -
  ...
```
````

However, all the parts of the file (here, the first line) that match the first regex don't appear in the compiled file. If I replace that `embed: scope:source.bash` with [a context defined in the same file](https://git.dblsaiko.net/web/tree/global/Console.yaml?id=26ddf3b39177dbb4668e9550a0e71888f63c2d72), it works.
