### ISSUE TITLE
Allow filtering symbols by math class in the General Symbols page

### ISSUE THREAD

**Issue by MDLC01** [typst/typst#8265]
### Description

In the [General Symbol documentation page](https://typst.app/docs/reference/symbols/sym/), allow filtering symbols by math class.

Currently, this can be achieved by adding the following CSS rule to the page, (where `<class>` is replaced by the class). Of course, this is less than user friendly.

```css
.symbol-grid li:not([data-math-class="<class>" i]) {
  display: none !important;
}
```

### Use Case

Finding symbols more easily when you don't know what you are looking for exactly, but want, e.g., a new notation for a relation. For example, this may be useful by the kind of person who defines many relation, such as in https://github.com/typst/typst/issues/6028.
